title: GDAL Tutorials
description: Scripts and tests for the GDAL Tutorials
theme: slate

baseurl: ""
url: "https://geographika.github.io/gdal-tutorials/"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files/folders from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
