name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch


permissions:
  contents: write  # required for pushing

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          # Use faster GNU tar
          enableCrossOsArchive: true
          path: D:\conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Set up Miniconda on Windows
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: gdal
          environment-file: environment.yml  # Optional, if you have one
          python-version: 3.11

      - name: Version Details
        shell: pwsh
        run: |
            conda --version
            gdal --version

      - name: Create output folder
        run: mkdir ./hillshade/data

      - name: Run hillshade
        shell: pwsh
        working-directory: ./hillshade/data
        run: |
            ../hillshade.ps1

      - name: Copy output
        shell: pwsh
        run: |
            mkdir output
            Copy-Item -Recurse -Force docs/* output/
            Copy-Item -Recurse -Force hillshade/data/*.tif output/

      - name: Deploy to docs branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: docs  # or gh-pages
