name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          # Use faster GNU tar
          enableCrossOsArchive: true
          path: D:\conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Set up Miniconda on Windows
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: gdal
          environment-file: environment.yml  # Optional, if you have one
          python-version: 3.11

      - name: Version Details
        shell: pwsh
        run: |
            conda --version
            gdal --version

      - name: Create output folder
        run: mkdir ./hillshade/data

      - name: Run hillshade
        shell: pwsh
        working-directory: ./hillshade/data
        run: |
            ../hillshade.ps1

      - name: Deploy to docs branch
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --single-branch --branch docs https://github.com/${{ github.repository }} output
          # rm -rf docs/*
          # cp -r output/* docs/
          # cd docs
          Remove-Item -Recurse -Force output/*
          Copy-Item -Recurse -Force docs/* output/
          Copy-Item -Recurse -Force hillshade/data/*.tif output/
          Set-Location output
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push origin docs